# environment defaults internally to development
# however, consumers can override it using a custom values file.
environment: development
serviceAccount:
  name: ndtech-website
deployment:
  replicas: 1
  minReadySeconds: 3
  namespace: ndtech
  imageVersion: 0.0.1
  containerPort: 3000